---
- hosts: all
  become: true

  tasks:
  - name: "Update hosts file"
    lineinfile:
      path: /etc/hosts
      line: '{{ item }}'
    with_items:
      - '{{ control_node_ip }} control'
      - '10.10.1.11 worker-1'
      - '10.10.1.12 worker-2'
      - '10.10.1.13 worker-3'

  - name: Make sure group wheel is not in the sudoers configuration
    lineinfile:
      path: /etc/hosts
      state: absent
      regexp: '^127.0.1.1'

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      state: present
      update_cache: yes

  - name: Fix docker cgroup driver
    lineinfile:
      create: yes
      path: /etc/docker/daemon.json
      line: '{{ item }}'
    with_items:
      - '{'
      - '  "exec-opts": ["native.cgroupdriver=systemd"]'
      - '}'

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /etc/containerd
      state: directory
      mode: '0755'

  - name: Install containerd
    apt:
      name:
        - containerd
      state: present
      update_cache: yes
    notify:
      - containerd status

  - name: Configure containerd
    ansible.builtin.shell: containerd config default | tee /etc/containerd/config.toml

  - name: sed line in containerd config
    ansible.builtin.shell: sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

  - name: Restart containerd
    service:
      name: containerd
      daemon_reload: yes
      state: restarted

  - name: Disable swap
    command: swapoff -a

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt:
      name:
        - kubelet={{ k8s_version }}-00
        - kubeadm={{ k8s_version }}-00
        - kubectl={{ k8s_version }}-00
      state: present
      update_cache: yes

  - name: Configure KUBELET_EXTRA_ARGS
    copy:
      dest: /etc/default/kubelet
      content: KUBELET_EXTRA_ARGS=" --node-ip={{ node_ip }} "
      mode: 0755

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Copy the join command to server location
    copy:
      src: /tmp/join
      dest: /tmp/join-command.sh
#      remote_src: yes
      mode: 0777
    become: false

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh

  handlers:
  - name: containerd status
    service:
      name: containerd
      state: started
